# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.0.0-canary.1 (pinned to v1.0.0-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.0.0-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT100Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.0.0-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "c81cb570b703895d7ddd95f2f7b2662e0b39b6cc0601e3a426e5e4870ab20125"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "0123fc608118d8e97f466422be8fbd26a9d4c935399ee761913fb0c8408ff847"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "66219d9c86c0242dc03a990415e5756913ef7837a3282e44f1d2dd9eb67cc7af"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "c1301c89d213802626ce98c28401ebd53758c327794d830cbdb822e26fcd8887"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
