# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.5.1-canary.2 (pinned to v1.5.1-canary.2)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.5.1-canary.2
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT151Canary2 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.5.1-canary.2"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.2/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "5a100224422a4c94b9184ba4b738d878e6373f45d9ed5144bf22cd89dbe48186"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.2/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "2257b7e4c523dc39fffc2244df2ab73f7b545e937b162663911d4cec498fdff7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.2/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "64700c94f1acf565ab3721f567f05461160901d238081908a51c58ac73931681"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.2/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "178fb172fec4eaa06769d9695583496c38489e072188ff9382a82c544c3e0a34"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
