# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.1.0-canary.5 (pinned to v1.1.0-canary.5)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.1.0-canary.5
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT110Canary5 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.1.0-canary.5"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.5/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "ee9cc409b663d2e2101b21f90d4f1d65563131705f6ea850f8d1c9605b6a9429"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.5/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "e0239fba3e5981af8793fba5d4a728a50b13e9ba987b80f58b50983d7937cbed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.5/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "f06db71677e1b6777b5c2ec6ac2c3ca0b7d0ea7e92cc1773bec088d67533b2bc"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.5/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "bfa20a0a09d1a4bf2b6f220c1b5e7846571121f99f2321e9253a743ca4aafde1"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
