# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.2.0-canary.1 (pinned to v1.2.0-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.2.0-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT120Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.2.0-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "de18129c0f82fa4116fc8e1d2bdc742c86e2ed402f1cee4541b9dfb88d6351dd"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "0bf8a11cfef9203ed7a4a706a95dbe7dcdba72f9ecc2210542072831d526dade"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "156d34084595dea1f1836350fb7a809da42ee30bf8640545e9f72ab77423c9c3"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "78289f369172a778a6bfff3008ce1645af4eaef68dc9e79ff56b52dd458c7cf3"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
