# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@0.9.3-canary.1 (pinned to v0.9.3-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@0.9.3-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT093Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "0.9.3-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.3-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "172f48498e4bfa0cfe66dcf74a50ccb9ef421d611b9b4f12544cdbc5e2f43ca0"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.3-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "4f55a302984aba6a8e96b489cbd351b4a87fe247ca80db645ea64608ce65394d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.3-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "67c83399261224b9012ca00843cbb50a187c1c9c7afc8a134f58535e63a2b3a8"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.3-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "7cf332cb5bbde3402b3f9f0e58566b4f781cca700552af7769494fafb10f260c"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
