# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.1.0-canary.8 (pinned to v1.1.0-canary.8)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.1.0-canary.8
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT110Canary8 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.1.0-canary.8"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.8/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "be9788f4e2bf8e55faceae682092cd9a82568ba3da0a354124ab82a88a2d3bed"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.8/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "4e6247471298a5ba23a269aa26363e1181b1367b6b4a4064e16b0b6dc64d4bda"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.8/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "03be53c94cd29a55db7d9536227012da4d6be9417dfa17abf930518adf21e335"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.8/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "ac0e51d65cee78e46af928f16d7c80ede563ecd3ae9ca02a469c54fee6e46c54"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
