# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.3-canary.7 (pinned to v1.3.3-canary.7)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.3-canary.7
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT133Canary7 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.3-canary.7"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.7/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "a923f8881efe2c5870421f0cc547df969296523e2833a2df65ca209c57f6fd0d"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.7/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "86c3973323b662a3b0b162e6e9c5337bea6f59a1f1372198ef49b884dea0ccd1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.7/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "09d51f8ff890d436ae3802293d46134c5f6f948f00df4797e23a729ded1c5782"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.7/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "070c046eb1b9433ae3ea33cd6c9542bcac8f0e3cbb7ab5ab1baf9df91faba7d1"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
