# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@0.9.2-canary.3 (pinned to v0.9.2-canary.3)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@0.9.2-canary.3
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT092Canary3 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "0.9.2-canary.3"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.2-canary.3/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "0e8267bedebceaac79ef9f3221dc962c1152320d36eae824e5ce94821c417855"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.2-canary.3/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "9e74358950e51f111fabed5e06d94986e8420c4f2d4df23ffb98ec1f410291cd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.2-canary.3/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "194c58b9cac27bf7480935c1f4ab43e2688fa78eeda38323c509ac1f4e274973"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.2-canary.3/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "c69c203c07b8de473fc2fc1925efcc008d15170bb333bd6ac896b8ce331cb571"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
