# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.0.0-canary.2 (pinned to v1.0.0-canary.2)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.0.0-canary.2
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT100Canary2 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.0.0-canary.2"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.2/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "2adc49d5c0031a899ab9580cb38cdae47e5b797564be36164886b5e74df79c7f"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.2/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "9a543cf4391fe7d84f1a573247c71076579b2854abbfa363d9c0e069d1069b2a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.2/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "d3bb1be39813156d6e39edb92ca95a39699073d011dc1ecdbd49d1e01d49df7a"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.2/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "8221efb8a2bcc5db44c6cf3dba921eaa45d913780e28779a720029a5ecd3cd3c"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
