# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.8.1-canary.1 (pinned to v1.8.1-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.8.1-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT181Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.8.1-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.1-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "f0da7db85a8cab1df241f279fe28215705f6c703ae59bf91c7adc1f5d783e9e0"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.1-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "f620b57f1a154facb7dc86b44bfb9e806455ae25c5700722acaaa6a949394e41"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.1-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "b52cd6301f2fce93edad6fcc1d7fb3b8e078063896b29f50d337bc9490c6d4e6"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.1-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "220c4bc4d6c3e94420beb95e50d1a36ffaf8637669690be1c9088b78162d5893"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
