# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.2.0-canary.5 (pinned to v1.2.0-canary.5)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.2.0-canary.5
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT120Canary5 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.2.0-canary.5"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.5/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "99c1b1bf81b4c2185540c772e0550390624a2eaacf8b3d50cccc0027f07076a3"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.5/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "c858881b0e19396c1dc6267f10829c14bcc8d342fe5dca69373ed167dc799b26"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.5/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "e3810f9c1cbe3dae371868afd418df39debd921789093a90f1c61fe3ca6f81c9"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.5/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "f09d6630cd9bf790c89e396374b82744dff341172e01135392c87139f6d4ab50"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
