# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.1.0-canary.3 (pinned to v1.1.0-canary.3)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.1.0-canary.3
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT110Canary3 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.1.0-canary.3"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.3/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "b6305a532d7b4a06e3b20a615e30dc8ea3b1a4f01ed1a634b5cf0380956dc454"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.3/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "ab910fdb2004f8559fff25af68c5262e1b685bb771bc4ea974d1b8eb623b4bd0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.3/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "e8eb59e6f81bf36af75e92108ef03f900ba4610b289aa7b2adbe5b6e50b557d2"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.3/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "d850aded4b4722e9e79c9879be96408c3aa9feb366704252ec74a6cafb763443"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
