# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.3-canary.2 (pinned to v1.3.3-canary.2)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.3-canary.2
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT133Canary2 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.3-canary.2"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.2/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "d2d666a09262482390c5209c50512d44769d12c56f6338da352ac88e3b019b7d"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.2/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "b892efc12aa33647b90d9ce85b471a87e3df776f69283392e81bf98115414d62"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.2/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "0f59c4e7cba35eda3aaab4905ed344c2701473ebe2cff51714a43def9d041b2e"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.2/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "753d81ac48f6a18fde2064daaa7cf5918e41c53f20d2d0352a3f184bf6a7dc9c"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
