# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.5.1-canary.3 (pinned to v1.5.1-canary.3)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.5.1-canary.3
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT151Canary3 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.5.1-canary.3"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.3/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "e1bbd55fde4f732abc79529a08311afee2cbc83bd9aa672c49d3d873728b1d31"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.3/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "8654debb040a1acffb5a9a2bbd69cc0a86cbf68e82cb076ccbf4d745b3c931bd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.3/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "968f110b42ec7834c86abe7bd84d0fc4c2579424b9127e29afe6fcf2c636ef25"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.3/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "121bce2e7a2d8bc549243140c7e7f4d6d97792e21e49e52b7a186ccd7ff101fe"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
