# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup@1.0.0 (pinned to v1.0.0)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup@1.0.0

class MkvdupAT100 < Formula
  desc "Storage deduplication tool for MKV files and their source media"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.0.0"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0/mkvdup_darwin_arm64.tar.gz"
      sha256 "1d8fe2fb2d16d9a6348574bc26e035d6e85510a5a12ebee1239485ac46bb6008"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0/mkvdup_darwin_amd64.tar.gz"
      sha256 "ff0e0f04123c959011998b03372484e6120571d4ec20f5ac9806cf687a4d49be"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0/mkvdup_linux_arm64.tar.gz"
      sha256 "0b428c2d3c23c10da0c194414dfa67bd991de56437ab0b6be69f4a61ddef4778"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0/mkvdup_linux_amd64.tar.gz"
      sha256 "297ef62beae55fa2528cc6950b57106cc4d140fe0b731294f1aa1cea83c0e485"
    end
  end

  def install
    bin.install "mkvdup"
    man1.install "mkvdup.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup"
    fish_completion.install "mkvdup.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup --version")
  end
end
