# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@0.9.0-canary.23 (pinned to v0.9.0-canary.23)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@0.9.0-canary.23
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT090Canary23 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "0.9.0-canary.23"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.0-canary.23/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "16f5e8ba955ccd5b1b71c99a6653130c0154712003758041a559c1df85b00b27"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.0-canary.23/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "c83c73bc06996fea65cdf9a2d561921b90341c73ca8f01ada6cba4e0bf0ce54f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.0-canary.23/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "38a1edbd2a55e3fb6e8bac68793f7d7950682148c426527641b958c85a148cda"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.0-canary.23/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "927e17446fc4e381fb52f8edfb90202f6ac8a23f55737d46ef1be81d61951804"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
