# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@0.9.2-canary.2 (pinned to v0.9.2-canary.2)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@0.9.2-canary.2
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT092Canary2 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "0.9.2-canary.2"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.2-canary.2/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "f4d967cb57c2d9bf61273fa6e0a665b374dde1734c4f26104bfdb4a91b5a89d5"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.2-canary.2/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "5f087c0cd1216b8348b7993e50ac78db566720ac69c3768171239e9385a21a1c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.2-canary.2/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "f5ee99579292013063142e08f50a71db436502e2d4a7e833e49ea268368dfb80"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.2-canary.2/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "beb1c870536167a649cc573f60174b654aff691f86aac3af16f7be64637c9823"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
