# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.5.1-canary.1 (pinned to v1.5.1-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.5.1-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT151Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.5.1-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "cd65be3f7f504e85d90c4def49eaa27afa6c0036fd074aafa508b60c9bbf0f52"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "fc1b3ab2e292eece4f728c5ba595ddf906d40df45f0fbd47edd1d5df32d20137"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "8b879768c02052c59f3a014a9adf8261a907bd1035e290beb0baa537ea5762fa"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.5.1-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "53c7021778c423b5743e12dfd5937539e907498c34e3226e9deed0479af25fc7"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
