# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.0.0-canary.5 (pinned to v1.0.0-canary.5)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.0.0-canary.5
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT100Canary5 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.0.0-canary.5"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.5/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "58f5d5fe9a69d5c9650dc54253d3239972d5029208b5739daec4a737f269472d"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.5/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "d2e5ac7b991b7a6372c6147b6923e44dfd9b25780e1c7553b4ca0fe9415b58d3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.5/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "af3b6f2c6f6c2a3d870d8fe72363f5f8aadd64be01888097f9c36f841aa302dd"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.5/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "9610b0ccbfa755a601c6ce7372f69bd2a3b5c6b14b0a0d2738b0aa8d50670afc"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
