# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.3-canary.3 (pinned to v1.3.3-canary.3)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.3-canary.3
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT133Canary3 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.3-canary.3"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.3/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "2de402014528e13697bf53a14701d3c5ba34a78382f1be07799e7d056d1cd27a"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.3/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "00c2ead90c78b24264042725160c5c134faac4203ee464095de79abbe997626e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.3/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "fdeefc250d3a78a430d2dd25d373f65e4e1fd3bc7e41e1bbcd653b2f25bb0b9e"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.3/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "c86704072afac3f28750b4c2d9fbf975621c8d77b46ad0a4ace5dc2fdec49dda"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
