# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.2.1-canary.1 (pinned to v1.2.1-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.2.1-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT121Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.2.1-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.1-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "f388e46bac962a15f2bc206d2430a251c97328a9278243ee7b3454458a698e6e"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.1-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "4eae72facaab91e83df8eaed494a9ba4b91f6552030b5677f8e7f233bc4afbbc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.1-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "7ef51e2dcbcfad3618f96973420fb4c39780eb2a69aeb516fd43b9f3f671d84f"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.1-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "404f693843b7d33593e5c5977ee7dfe5a34fa9dfef0b73484e6b4cc44efc23ed"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
