# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.0.0-canary.6 (pinned to v1.0.0-canary.6)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.0.0-canary.6
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT100Canary6 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.0.0-canary.6"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.6/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "2ff669435f3bb597d2dfe60b69d553763ce60a5ebcb4d48984e424e1fed0aec2"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.6/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "13e8ca9b1e509e901839b7dd31c805e093532ded9e94c051ac8de0dc868ff1e9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.6/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "d0b5c13dff6d10ac33d8ae8dd2c00b5217387e04ea58dbc6e1a6b2539ae562fb"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.6/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "91082e9518342416ca101abe134f37880096d7aaccb4d55793b2585891109046"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
