# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.3-canary.5 (pinned to v1.3.3-canary.5)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.3-canary.5
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT133Canary5 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.3-canary.5"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.5/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "ab3fba9bc76f7093e681b02404809ca0f121479cb392aadba13a9b27da36405e"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.5/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "471eff61eb34ceecfcb5590d217cfdd35c551a310f8e3bd9b06796487fb4efd6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.5/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "4a515e1450cbcc6143a9951d4a1bc4c42b965ee532adf0ccd5f27840ba105df6"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.5/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "f52217320dfe3e8fc13669576daf3c6329a582b0baf3aa43beddbe85523be694"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
