# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@0.9.4-canary.1 (pinned to v0.9.4-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@0.9.4-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT094Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "0.9.4-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.4-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "1c1cb7a6a1410b77f6f1f0ff8ceebe1fc70a7eecca55535169fa13ca8d172524"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.4-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "6007fdc341bd441749279337fbbf729cac3bb5a60d088e6139d106b3e021f9cc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.4-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "9125d8ea8ab6b2e5079bf24accffffac8f656c681505c98f6b5474e45e478c45"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.4-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "95719afd00200c70a211a4be7cabe0010ed154cf5cd1e5304445b45a4c67a87d"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
