# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.1.0-canary.1 (pinned to v1.1.0-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.1.0-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT110Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.1.0-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "c7bfce8be21df3f5c1abe0ae1b56fe85506db0073b824bb407a41299e543dad7"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "3b2987b83ae8cff81a468a35a92f43145119eb88d511805a9e5e84a071e7f813"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "69ea065710234e108fcee5b17d73c1b1a9d8f0e5322063772829df4d30775acc"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.1.0-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "da15a5a58b0bde03118b93a424f82172a972655d5122f06c06de29d144eb389c"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
