# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@0.9.1-canary.1 (pinned to v0.9.1-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@0.9.1-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT091Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "0.9.1-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.1-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "d090e2ce4a1469e11e038aa93db00f0566ef11643efd67a29818b92ef3474ca0"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.1-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "43b369b1ec0b7dbb069a31785a2e5b42aa3fc02277f9f25961106cb3568b1763"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.1-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "60f9edf8730dc113c7686ca7067da85adc389697485e63b51c720afb68ad90fb"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.1-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "61fc8aba4988bf93e432eafc6cb0654f30077a2d374b039bdb623be1301eb6f1"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
