# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.3-canary.4 (pinned to v1.3.3-canary.4)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.3-canary.4
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT133Canary4 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.3-canary.4"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.4/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "1f3a0b829396ef6f9dd3beb6450adf394ef6098073e6e42b650e93f98df2a945"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.4/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "ea3febcc9cee71de2a7f8752143b08054b5e30cb812ab47556052b13fb1c1dc6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.4/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "82d0dc6dfa12d6f03abb56e420db243d39da06aa9d8684735f4fed66acc14146"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.3-canary.4/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "c77dbac7fb8b4fce9a033b0376febd42adb2d6052cd46b9b9c4ea7c63b7b4d8c"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
