# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.1-canary.1 (pinned to v1.3.1-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.1-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT131Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.1-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.1-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "e929d980328815ce62335c132cd6094c7fe65e7a4268ce43f305cdc03fbc3871"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.1-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "5230f18452a36fdb3f6bc79e5d039157bf7bc4f32343c1045c76500a52f4234e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.1-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "1847aeb3619b817d0fda2ef87c64879eb6096895524abb98d292dfb38e4a572b"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.1-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "cf129c12490e4d17ddb6d3ac44da61b05497fc64a2c51c2d8b2f77de25616f94"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
