# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.6.0-canary.1 (pinned to v1.6.0-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.6.0-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT160Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.6.0-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.6.0-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "473dd664d720d458258765158676dc225eafb9ae4807dfd970ef30208a3b3245"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.6.0-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "8aa483ee9154b3252b8849d7d9c22da453924dc8bf3644416af3f1cd7a406b6a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.6.0-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "f5c6bdb853fab84e67f41d27c8447a0bdc723f784a77a4e83eaf741a3d2093d9"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.6.0-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "231db21e6330fb520ecb221f2b318561f99ad98fabe00709cd2483f2fd5010e3"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
