# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.8.2-canary.2 (pinned to v1.8.2-canary.2)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.8.2-canary.2
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT182Canary2 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.8.2-canary.2"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.2-canary.2/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "97bfbfd2d32cc25263e3666f7c52c29ea868c5db017475d31dbb962b2f334e58"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.2-canary.2/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "9e7443629038c921b4b86f095361ea5dc99fcde4124ce6e88d2ae3ebfa324cc5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.2-canary.2/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "4bf6bf6ba2ba892878d154c7b678992494b1e63b8c4896c0e191a627017e00b7"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.2-canary.2/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "709c47386765998c0f0df622b5b8854531c3a203ce8fbb34430f2116616c3482"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
