# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.2.0-canary.7 (pinned to v1.2.0-canary.7)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.2.0-canary.7
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT120Canary7 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.2.0-canary.7"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.7/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "d1698ebf42fa8e28da17665614537047e59281fdb0d3047348a0213c4a967ead"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.7/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "ea5fca61ecba3c3acfc456cc8a33ee13bb287b26d6d82f6ef775d5cc976893bc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.7/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "a5e4e96704cb93c2d88bc1274931d67209de04618ccdc74bcba20b0ea96b57a3"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.7/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "a3600ca215493b6a8baa33aacee69a8e63082665a2e76bd564dd01aa4003e16b"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
