# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup@1.8.0 (pinned to v1.8.0)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup@1.8.0

class MkvdupAT180 < Formula
  desc "Storage deduplication tool for MKV files and their source media"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.8.0"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.0/mkvdup_darwin_arm64.tar.gz"
      sha256 "7253acf48419cae8355e329670bb3c72ad98f9f33dea4fd28af19bbd63d8207f"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.0/mkvdup_darwin_amd64.tar.gz"
      sha256 "2b160000919a41770031f89de9a0545caf64442504a1f691633e4214701d2a05"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.0/mkvdup_linux_arm64.tar.gz"
      sha256 "dc72d32f73257929909e509b71f6e109716b2141c5b6e68c890dee707c110939"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.0/mkvdup_linux_amd64.tar.gz"
      sha256 "7f360c3ca4e8e625a3ed8d723fed6e258a98662c510ae031922889ac90b2242c"
    end
  end

  def install
    bin.install "mkvdup"
    man1.install "mkvdup.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup"
    fish_completion.install "mkvdup.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup --version")
  end
end
