# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.0.0-canary.4 (pinned to v1.0.0-canary.4)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.0.0-canary.4
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT100Canary4 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.0.0-canary.4"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.4/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "aed21926ced4895454c4a575bb0163048d736c66f07ec83504e6acf067638804"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.4/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "40e32f17024bcdedb9724a0fe24c9e2e7e8b838dbb609165034b23202e949989"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.4/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "2343e7e42fef29a6902f3697a0fff6aba10c17b9c4150ffcb8962a58d18ef0bd"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.0.0-canary.4/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "5a799896ee0e589651518030ae66f85fcb5dd40043fdf5117a748fc40a05e4f7"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
