# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup@1.8.1 (pinned to v1.8.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup@1.8.1

class MkvdupAT181 < Formula
  desc "Storage deduplication tool for MKV files and their source media"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.8.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.1/mkvdup_darwin_arm64.tar.gz"
      sha256 "9bb1dabadb989bad1520f72bf13efacdc09d221e43891ccdfeae1b6eb1f2af20"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.1/mkvdup_darwin_amd64.tar.gz"
      sha256 "0ed78356d3fd9f8f2b775afbba7c1b8021c31ec69d7594bc12bd7164a92e5426"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.1/mkvdup_linux_arm64.tar.gz"
      sha256 "d11a3e21f1d781a3e3c7db1fd85f187ee075ed33d2dc022e11f146279a31af51"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.8.1/mkvdup_linux_amd64.tar.gz"
      sha256 "dbc3e73cc5adaee1a5b59c29471e9fdd7f1187dd1d442bff271c969f318f803f"
    end
  end

  def install
    bin.install "mkvdup"
    man1.install "mkvdup.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup"
    fish_completion.install "mkvdup.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup --version")
  end
end
