# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.0-canary.4 (pinned to v1.3.0-canary.4)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.0-canary.4
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT130Canary4 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.0-canary.4"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.4/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "df3d2cb2d3c8fc6889c0ed39347d70b1ce03cb3fc66f8cf49fef21159145df6a"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.4/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "01a7a4d769aeade7aa1680c11c9450438b94f978673816c6cf6efc381f6ca03b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.4/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "e4cc75c3e8058eb5ef48cb8f2af12cced62be8362fd23b400263f178adbc483b"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.4/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "2515d8b548f1ab3b636abefd12ed919e3951637ed55e9058e033a28c5b799876"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
