# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup@1.6.3 (pinned to v1.6.3)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup@1.6.3

class MkvdupAT163 < Formula
  desc "Storage deduplication tool for MKV files and their source media"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.6.3"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.6.3/mkvdup_darwin_arm64.tar.gz"
      sha256 "f421e6def72e9b4c7243c7bd4471d89322cd0155cd192a2895f2e50650137bfa"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.6.3/mkvdup_darwin_amd64.tar.gz"
      sha256 "1b52991e08e4beab1b140b0a1d40b220be9f348c1fcda02118f3faca2c9011d9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.6.3/mkvdup_linux_arm64.tar.gz"
      sha256 "1e304a6db1376b0c769e3f3ddc939bc5b766a1032bdadb7cb4ebab7bdfdc3d18"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.6.3/mkvdup_linux_amd64.tar.gz"
      sha256 "24462ab35ec7753e8106538ddf055114c5270cc9931a0a372546c0a6a0650185"
    end
  end

  def install
    bin.install "mkvdup"
    man1.install "mkvdup.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup"
    fish_completion.install "mkvdup.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup --version")
  end
end
