# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.0-canary.2 (pinned to v1.3.0-canary.2)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.0-canary.2
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT130Canary2 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.0-canary.2"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.2/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "3bf456e5e82c5130e12272b57bdabdaf3606a08c51ff8853d95f7374bbb6979e"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.2/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "0121c500c87ac13c32638275fcdaa991c17aa7f9cb604a04d266e7e2b4d54c89"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.2/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "27d32c66b452c7b489e8c339afc76e89de455ad63f2c6d3d71d7dae141a91882"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.2/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "4ab5bb5ab329c6632312ff3293ed6556622e1ac4224fc99610a7eaa08ffded13"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
