# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup@1.3.2 (pinned to v1.3.2)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup@1.3.2

class MkvdupAT132 < Formula
  desc "Storage deduplication tool for MKV files and their source media"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.2"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.2/mkvdup_darwin_arm64.tar.gz"
      sha256 "6e09889a6909f289f613abcd452d9b5d17506d74475ec7b1c004034dface20fa"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.2/mkvdup_darwin_amd64.tar.gz"
      sha256 "bd880532f67c46dd1e638347568e13bfbeda0d4a08f776258d9a88a3139384ca"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.2/mkvdup_linux_arm64.tar.gz"
      sha256 "516e9698e9cbaa34f2f6fdac20a68603a60950d30d0f383841cb2899382646d3"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.2/mkvdup_linux_amd64.tar.gz"
      sha256 "867957601eb8fb9ed9c8c574c9bda1dc270fba5b3a7aca49de8222d721843401"
    end
  end

  def install
    bin.install "mkvdup"
    man1.install "mkvdup.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup"
    fish_completion.install "mkvdup.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup --version")
  end
end
