# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.2.0-canary.2 (pinned to v1.2.0-canary.2)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.2.0-canary.2
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT120Canary2 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.2.0-canary.2"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.2/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "47bc980b4837952891f61b43ba2af45f5731b13834daba74a6330f1e3303889e"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.2/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "c3263e45081296713cc94779e637cf6dbd7fe462608c60667e8806744c5d0ea0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.2/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "b908f13f594cf0f4619aaee99c271439357c5304f56c2992fbe96c4c1cea4905"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.2/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "e3facd8628a32f3e1116f43049a960774dc92a4deead21a60f90a69df94b68cb"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
