# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.0-canary.1 (pinned to v1.3.0-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.0-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT130Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.0-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "0ff581593395e80441dccb2c332cd0fc5a5480ec46a1370cd604f1bf1eb81c64"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "16b2a524ee62d661c6c4bbade29b1d873e38f76c22ecffef73f22ba71b63d9f9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "fa879a5e2c6d4d3b7f03d2f65eb84ab84756707a8c5d042ae0aa0c463d039624"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.0-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "7af4a1de810606a44094c8a164b23f1e7c66d9be681ede500dfcad63207fe97e"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
