# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@0.9.0-canary.24 (pinned to v0.9.0-canary.24)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@0.9.0-canary.24
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT090Canary24 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "0.9.0-canary.24"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.0-canary.24/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "40bacc2df4da908c178f3d88e6f8e85af54ffdedf9e62472adf21f5c6cfff0fc"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.0-canary.24/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "9bde72d67fc5aa4323c3cf661a8c57059ae390d02f12f6135d9a1079ea2928d7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.0-canary.24/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "72dd3f7a3ebd9c1a0a4994cd1dbb8be097e865360e9120a522c329ca3e1e934d"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.0-canary.24/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "f2bab6f16be8f93321ebd463dae00cf4d9b7721fc260c9034a03b7013f81df16"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
