# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.3.2-canary.1 (pinned to v1.3.2-canary.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.3.2-canary.1
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT132Canary1 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.3.2-canary.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.2-canary.1/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "fd9fb65b2e25a7d5a214b81a42dcec02357d10246fcc54b3d8156fa2dcd3dac7"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.2-canary.1/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "c8f5538bc3562b1846926c219f5bc7c46841b7628183935c1ac5718aac978d79"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.2-canary.1/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "9e91c06e592e29be74f3ccd0b6fabdeb555e1c85d20b24a6b2f41ddc08ac024d"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.3.2-canary.1/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "5929a897fb9f62dbef514890bb3dd0359b4074d3edc0e118d36c0e2b463795db"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
