# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup@0.9.1 (pinned to v0.9.1)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup@0.9.1

class MkvdupAT091 < Formula
  desc "Storage deduplication tool for MKV files and their source media"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "0.9.1"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.1/mkvdup_darwin_arm64.tar.gz"
      sha256 "9de547601af8fc7ec80a459be1d7f85918a1c2e7a15bf5ebd673ec70448eb499"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.1/mkvdup_darwin_amd64.tar.gz"
      sha256 "609d41164f3170845fc52e95a63ff7ec3cad66b15919ee8c19fa0eeaf3a9460f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.1/mkvdup_linux_arm64.tar.gz"
      sha256 "b3e18e97d4f75983842afae7bef0afba95eba49fbb82e21202640624711db075"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v0.9.1/mkvdup_linux_amd64.tar.gz"
      sha256 "49f88354d5c53f8ed8b72f5bb1c6876f3587b87d5983423ff79c32e2f2b72ff2"
    end
  end

  def install
    bin.install "mkvdup"
    man1.install "mkvdup.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup"
    fish_completion.install "mkvdup.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup --version")
  end
end
