# typed: false
# frozen_string_literal: true

# Homebrew formula for mkvdup-canary@1.2.0-canary.4 (pinned to v1.2.0-canary.4)
# This file is auto-generated by the release workflow.
# To install: brew tap stuckj/mkvdup && brew install mkvdup-canary@1.2.0-canary.4
#
# The canary version can be installed alongside the stable version.

class MkvdupCanaryAT120Canary4 < Formula
  desc "Storage deduplication tool for MKV files (canary/pre-release)"
  homepage "https://github.com/stuckj/mkvdup"
  license "MIT"
  version "1.2.0-canary.4"

  on_macos do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.4/mkvdup-canary_darwin_arm64.tar.gz"
      sha256 "243cbf5c00d83dc9388850340b60b05da4e1a75ba27789960bb3fd4bf842dd49"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.4/mkvdup-canary_darwin_amd64.tar.gz"
      sha256 "07a3a76b50792af82b093f8a4c684b096778ddcca7261b5bcb592fa0debd9d41"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.4/mkvdup-canary_linux_arm64.tar.gz"
      sha256 "543b91b351efffea8ca0d5460d4d3894d7a516c1eda5f7df9ce19bd8017fe7c2"
    end
    on_intel do
      url "https://github.com/stuckj/mkvdup/releases/download/v1.2.0-canary.4/mkvdup-canary_linux_amd64.tar.gz"
      sha256 "b14141fca24ce8e0fc858192109125b4e22052cd7a73a8754fec4bf4676dcdaf"
    end
  end

  def install
    bin.install "mkvdup-canary"
    man1.install "mkvdup-canary.1"
    doc.install "README.md", "DESIGN.md", "LICENSE"
    doc.install Dir["docs/*"]
    bash_completion.install "mkvdup-completion.bash" => "mkvdup-canary"
    zsh_completion.install "mkvdup-completion.zsh" => "_mkvdup-canary"
    fish_completion.install "mkvdup.fish" => "mkvdup-canary.fish"
  end

  def caveats
    <<~EOS
      This is the canary (pre-release) version of mkvdup.
      The binary is installed as 'mkvdup-canary' to allow side-by-side
      installation with the stable 'mkvdup' package.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mkvdup-canary --version")
  end
end
